### PR TITLE
No ticket update npm access token

### PR DESCRIPTION
**Pull request by BirgitPohl**
- Updated NPM access token
- Removed some NPM vulnerabilties

### CODE REVIEW

**Review by vmorgado — APPROVED** [review]

**Comment by dknx01** [comment]
Did you downgraded some packages by accident? In the lock files I see a lot of downgraded packages.

**Comment by BirgitPohl** [comment]
@dknx01 npm audit --fix is all I commanded. 
It may be that in later versions those vulnerabilities have been introduced and the automation says, it is save to downgrade a package.

**Comment by dknx01** [comment]
Can you please verify this?
I don't like and not really trust it if packages are just downgrades by a command.
That's also a reason why I would like to have these fixes in a separated PR, so we no it has nothing to do with the real ticket solution.

**Comment by BirgitPohl** [comment]
@dknx01 
Run npm run build on your local machine.
It will create some dist folders. You can go inside ./dist/ and view the .html file inside a browser.
You can compare this with the [demo page](https://assets.gcloud.fti-group.com/fti-group-icon-font/latest/fti-group-icon-font.html), which is stored on google cloud and only published after a PR merge.
Would it be the verification you are searching for?
All it needs from this repo are the elements inside the dist folders.

**Comment by dknx01** [comment]
@BirgitPohl the verification for me would be actually more like: looking at the vulnerability report and see what they say to fix it.
Somehow I actually doubt it, that you must downgrade to remove it, mostly the fixes comes with the next version. Maybe we have somewhere a dependency fixed to a version that causes than the downgrade and we should upgrade these dependency, too.

**Comment by BirgitPohl** [comment]
Update after having Claudia review the PR.
Only 4 moderate severity vulnerabilities left.

According to Claudia, the package-lock does not always downgrade the npm packages.
It can be looked up inside the node modules's package.json what versions they have.

For example: 
Line 31: "repeat-string": "^1.5.2" takes version 1.6.1 as seen in its package.json:
"_resolved": "https://registry.npmjs.org/repeat-string/-/repeat-string-1.6.1.tgz"

**Comment by cllagosr** [comment]
To summarize: 

- The change on package-lock.json has nothing to do with the command `npm audit --fix` but with `npm i --package-lock`

- Most of the packages were not downgraded (see: ~ and ^), the new package-lock.json is just the result of your current package.json created by np. So, your current version of npm tried to resolve the dependencies of those packages and changed them, probably you were already using it (this package-lock.json file) but because it was in `.gitignore` you didn't realize.

**Review by dknx01 — APPROVED** [review]

**Pull request merged**
